app = "my-openwebui"
primary_region = "fra"

[build]
image = "ghcr.io/jf-devops/openwebui:latest"

[[vm]]
cpu_kind = "shared"
cpus     = 2
memory   = "4gb"         # shared-cpu-2x max

[mounts]
source      = "openwebui_data"
destination = "/app/backend/data"

[[services]]
internal_port = 8080
protocol      = "tcp"

  [[services.ports]]
  port     = 443
  handlers = ["tls", "http"]

  [[services.ports]]
  port     = 80
  handlers = ["http"]

[registry]
server   = "ghcr.io"
username = "zer0dude"        # org or user that owns the image
password = "${GHCR_TOKEN}"    # Fly substitutes the secret at deploy time