# fly.toml app configuration file generated for my-openwebui on 2025-05-23T19:19:48+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-openwebui'
primary_region = 'fra'

# [build]
#   image = 'ghcr.io/open-webui/open-webui:main'

[build]
image = "ghcr.io/jf-devops/openwebui:latest"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
